package com.johansvartdal.landlord.levels;

import com.johansvartdal.landlord.Book;
import com.johansvartdal.landlord.God;
import com.johansvartdal.landlord.LangDict;
import com.johansvartdal.landlord.events.LandlordEvent;
import com.johansvartdal.landlord.Main;
import com.johansvartdal.landlord.events.arenafight.ArenaFight4;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

import java.util.ArrayList;

public class S2Level8 extends Level{

    public S2Level8(Main plugin) {
        super(plugin, 2, 8);
    }

    @Override
    public ArrayList<ItemStack> getRequiredItemsForNextLevel() {
        ArrayList<ItemStack> requiredItems = new ArrayList<>();

        // generated by ChatGPT
        requiredItems.add(new ItemStack(Material.TUFF, 40 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.SPRUCE_LOG, 70*Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.POINTED_DRIPSTONE, 23 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.COOKED_PORKCHOP, 22 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.MELON, 64 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.GOLD_INGOT, 19 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.SHROOMLIGHT, 4 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.BOOK, 16 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.KELP, 128 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.DEEPSLATE, 90 * Main.properties.getNumberOfPlayers()));

        return requiredItems;
    }

    @Override
    public void justUpgraded() {
        God.speak(LangDict.getString("levelBooks.season2.level8.godSpeak"));
    }

    @Override
    public int getRouletteGamePrice() {
        return 1100;
    }

    @Override
    public LandlordEvent getEventToStartBeforeLevel() {
        return new ArenaFight4(plugin);
    }

    @Override
    public Book getBook() {
        Book book = new Book("S2L8");
        book.addPage(LangDict.getString("levelBooks.season2.level8.page1"));
        book.addPage(LangDict.getString("levelBooks.endSignature"));
        return book;
    }
}
