package com.johansvartdal.landlord.levels;

import com.johansvartdal.landlord.Book;
import com.johansvartdal.landlord.God;
import com.johansvartdal.landlord.LangDict;
import com.johansvartdal.landlord.events.LandlordEvent;
import com.johansvartdal.landlord.Main;
import com.johansvartdal.landlord.events.adventure.LumberMineForestAdventure;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

import java.util.ArrayList;

public class S2Level7 extends Level{

    public S2Level7(Main plugin) {
        super(plugin, 2, 7);
    }

    @Override
    public ArrayList<ItemStack> getRequiredItemsForNextLevel() {
        ArrayList<ItemStack> requiredItems = new ArrayList<>();

        // generated by ChatGPT
        requiredItems.add(new ItemStack(Material.DIORITE, 128 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.OAK_LOG, 176 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.SAND, 117 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.COOKED_MUTTON, 5 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.PUMPKIN, 64 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.RAW_IRON, 16 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.WARPED_WART_BLOCK, 19 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.CHERRY_SAPLING, 37 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.BEETROOT, 34 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.CLAY, 28 * Main.properties.getNumberOfPlayers()));

        return requiredItems;
    }

    @Override
    public void justUpgraded() {
        God.speak(LangDict.getString("levelBooks.season2.level7.godSpeak"));
    }

    @Override
    public int getRouletteGamePrice() {
        return 1000;
    }

    @Override
    public LandlordEvent getEventToStartBeforeLevel() {
        return new LumberMineForestAdventure(plugin);
    }

    @Override
    public Book getBook() {
        Book book = new Book("S2L7");
        book.addPage(LangDict.getString("levelBooks.season2.level7.page1"));
        book.addPage(LangDict.getString("levelBooks.endSignature"));
        return book;
    }
}
