package com.johansvartdal.landlord.levels;

import com.johansvartdal.landlord.Book;
import com.johansvartdal.landlord.LandlordEvent;
import com.johansvartdal.landlord.Main;
import com.johansvartdal.landlord.events.arenafight.ArenaFight3;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

import java.util.ArrayList;

public class S2Level6 extends Level{

    public S2Level6(Main plugin) {
        super(plugin, 2, 6);
    }

    @Override
    public ArrayList<ItemStack> getRequiredItemsForNextLevel() {
        ArrayList<ItemStack> requiredItems = new ArrayList<>();

        // generated by ChatGPT
        requiredItems.add(new ItemStack(Material.GRANITE, 100 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.BIRCH_LOG, 64 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.COBBLESTONE, 170 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.HAY_BLOCK, 25 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.CARROT, 128 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.DIAMOND, 2 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.GLOWSTONE, 16 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.CHERRY_PLANKS, 128 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.SUGAR, 109 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.FLINT, 34 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.WAXED_COPPER_BLOCK, 56 * Main.properties.getNumberOfPlayers()));

        return requiredItems;
    }

    @Override
    public void justUpgraded() {

    }

    @Override
    public int getRouletteGamePrice() {
        return 800;
    }

    @Override
    public LandlordEvent getEventToStartBeforeLevel() {
        return new ArenaFight3(plugin);
    }

    @Override
    public Book getBook() {
        return null;
    }
}
