package com.johansvartdal.landlord.levels;

import com.johansvartdal.landlord.Book;
import com.johansvartdal.landlord.God;
import com.johansvartdal.landlord.LangDict;
import com.johansvartdal.landlord.events.LandlordEvent;
import com.johansvartdal.landlord.Main;
import com.johansvartdal.landlord.events.adventure.SibirianCottageWinterAdventure;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

import java.util.ArrayList;

public class S2Level9 extends Level{

    public S2Level9(Main plugin) {
        super(plugin, 2, 9);
    }

    @Override
    public ArrayList<ItemStack> getRequiredItemsForNextLevel() {
        ArrayList<ItemStack> requiredItems = new ArrayList<>();

        // generated by ChatGPT
        requiredItems.add(new ItemStack(Material.OAK_LEAVES, 144 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.SUGAR_CANE, 128 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.IRON_BLOCK, 2 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.EMERALD, Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.WEEPING_VINES, 20 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.WHITE_WOOL, 21 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.MILK_BUCKET, 4 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.HONEY_BLOCK, 7 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.EGG, 24));
        requiredItems.add(new ItemStack(Material.COCOA_BEANS, 256 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.PUMPKIN_SEEDS, 64 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.TURTLE_EGG, 6 * Main.properties.getNumberOfPlayers()));

        return requiredItems;
    }

    @Override
    public void justUpgraded() {
        God.speak(LangDict.getString("levelBooks.season2.level9.godSpeak"));
    }

    @Override
    public int getRouletteGamePrice() {
        return 1100;
    }

    @Override
    public LandlordEvent getEventToStartBeforeLevel() {
        return new SibirianCottageWinterAdventure(plugin);
    }

    @Override
    public Book getBook() {
        Book book = new Book("S2L9");
        book.addPage(LangDict.getString("levelBooks.season2.level9.page1"));
        book.addPage(LangDict.getString("levelBooks.endSignature"));
        return book;
    }
}
