package com.johansvartdal.landlord.levels;

import com.johansvartdal.landlord.Book;
import com.johansvartdal.landlord.God;
import com.johansvartdal.landlord.LangDict;
import com.johansvartdal.landlord.events.LandlordEvent;
import com.johansvartdal.landlord.Main;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

import java.util.ArrayList;

public class S2Level5 extends Level{

    public S2Level5(Main plugin) {
        super(plugin, 2, 5);
    }

    @Override
    public ArrayList<ItemStack> getRequiredItemsForNextLevel() {
        ArrayList<ItemStack> requiredItems = new ArrayList<>();

        // generated by ChatGPT
        requiredItems.add(new ItemStack(Material.OBSIDIAN, 9 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.ANDESITE, 64 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.MANGROVE_LOG, 23 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.DRIPSTONE_BLOCK, 4 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.COOKED_SALMON, 7 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.POTATO, 240 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.COPPER_INGOT, 160 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.NETHER_WART, 30 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.CACTUS, 70 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.BARREL, 19 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.BAMBOO_MOSAIC, 11 * Main.properties.getNumberOfPlayers()));

        return requiredItems;
    }

    @Override
    public void justUpgraded() {
        God.speak(LangDict.getString("levelBooks.season2.level5.godSpeak"));
    }

    @Override
    public int getRouletteGamePrice() {
        return 800;
    }

    @Override
    public LandlordEvent getEventToStartBeforeLevel() {
        return null;
    }

    @Override
    public Book getBook() {
        Book book = new Book("S2L5");
        book.addPage(LangDict.getString("levelBooks.season2.level5.page1"));
        book.addPage(LangDict.getString("levelBooks.endSignature"));
        return book;
    }
}
