package com.johansvartdal.landlord.levels;

import com.johansvartdal.landlord.*;
import com.johansvartdal.landlord.events.LandlordEvent;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;

import java.util.ArrayList;
import java.util.Random;

public class S3Level1 extends Level{

    public S3Level1(Main plugin) {
        super(plugin, 3, 1);
    }

    @Override
    public ArrayList<ItemStack> getRequiredItemsForNextLevel() {
        ArrayList<ItemStack> requiredItems = new ArrayList<>();

        // generated by ChatGPT
        requiredItems.add(new ItemStack(Material.GRANITE, 100 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.OAK_LOG, 176 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.POINTED_DRIPSTONE, 23 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.SUGAR, 109 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.COOKED_SALMON, 7 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.DIAMOND, 3 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.WEEPING_VINES, 20 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.WHITE_WOOL, 21 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.BARREL, 19 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.SUGAR_CANE, 128 * Main.properties.getNumberOfPlayers()));

        return requiredItems;
    }

    @Override
    public void justUpgraded() {
        God.speak(LangDict.getString("levelBooks.season3.level1.godSpeak"));

        // schedule tax payback
        long paybackTime = Tools.secToTicks(60*25);
        if (Properties.DEV_CHEAT_MODE) {
            paybackTime = Tools.secToTicks(7);
        }
        Bukkit.getScheduler().runTaskLater(plugin, this::payBackTax, paybackTime);
    }

    private void payBackTax() {
        Random random = new Random();
        for (Player player : Bukkit.getOnlinePlayers()) {
            int tooMuchTaxAmount = 40000 + random.nextInt(80000);
            God.whisper(player, LangDict.getString("info.prePaybackTax") + player.getDisplayName() + LangDict.getString("info.midPaybackTax") + Tools.formatCurrency(tooMuchTaxAmount) + LangDict.getString("info.postPaybackTax"));
            Bank.depositPlayerWithoutTax(player, tooMuchTaxAmount);
        }
    }

    @Override
    public int getRouletteGamePrice() {
        return 1200;
    }

    @Override
    public LandlordEvent getEventToStartBeforeLevel() {
        return null;
    }

    @Override
    public Book getBook() {
        Book book = new Book("S3L1");
        book.addPage(LangDict.getString("levelBooks.season3.level1.page1"));
        book.addPage(LangDict.getString("levelBooks.endSignature"));
        return book;
    }
}
