package com.johansvartdal.landlord.levels;

import com.johansvartdal.landlord.Book;
import com.johansvartdal.landlord.events.LandlordEvent;
import com.johansvartdal.landlord.Main;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

import java.util.ArrayList;

public class S3Level5 extends Level{

    public S3Level5(Main plugin) {
        super(plugin, 3, 5);
    }

    @Override
    public ArrayList<ItemStack> getRequiredItemsForNextLevel() {
        ArrayList<ItemStack> requiredItems = new ArrayList<>();

        // generated by ChatGPT
        requiredItems.add(new ItemStack(Material.OAK_LEAVES, 144 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.SUGAR_CANE, 128 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.IRON_BLOCK, 2 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.MELON, 64 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.HONEY_BLOCK, 7 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.EMERALD, Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.NETHER_WART, 30 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.KELP, 128 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.COCOA_BEANS, 256 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.PUMPKIN_SEEDS, 64 * Main.properties.getNumberOfPlayers()));

        return requiredItems;
    }

    @Override
    public void justUpgraded() {

    }

    @Override
    public int getRouletteGamePrice() {
        return 800;
    }

    @Override
    public LandlordEvent getEventToStartBeforeLevel() {
        return null;
    }

    @Override
    public Book getBook() {
        return null;
    }
}
