package com.johansvartdal.landlord.levels;

import com.johansvartdal.landlord.Book;
import com.johansvartdal.landlord.God;
import com.johansvartdal.landlord.LangDict;
import com.johansvartdal.landlord.events.LandlordEvent;
import com.johansvartdal.landlord.Main;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

import java.util.ArrayList;

public class S3Level3 extends Level{

    public S3Level3(Main plugin) {
        super(plugin, 3, 3);
    }

    @Override
    public ArrayList<ItemStack> getRequiredItemsForNextLevel() {
        ArrayList<ItemStack> requiredItems = new ArrayList<>();

        // generated by ChatGPT
        requiredItems.add(new ItemStack(Material.ANDESITE, 64 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.BIRCH_LOG, 64 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.COBBLESTONE, 170 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.CARROT, 128 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.COOKED_PORKCHOP, 22 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.RAW_IRON, 16 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.GLOWSTONE, 16 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.BOOK, 16 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.BEETROOT, 34 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.CLAY, 28 * Main.properties.getNumberOfPlayers()));

        return requiredItems;
    }

    @Override
    public void justUpgraded() {
        God.speak(LangDict.getString("levelBooks.season3.level3.godSpeak"));
    }

    @Override
    public int getRouletteGamePrice() {
        return 800;
    }

    @Override
    public LandlordEvent getEventToStartBeforeLevel() {
        return null;
    }

    @Override
    public Book getBook() {
        Book book = new Book("S3L3");
        book.addPage(LangDict.getString("levelBooks.season3.level3.page1"));
        book.addPage(LangDict.getString("levelBooks.endSignature"));
        return book;
    }
}
