package com.johansvartdal.landlord.levels;

import com.johansvartdal.landlord.Book;
import com.johansvartdal.landlord.LangDict;
import com.johansvartdal.landlord.events.LandlordEvent;
import com.johansvartdal.landlord.Main;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

import java.util.ArrayList;

public class S3Level4 extends Level{

    public S3Level4(Main plugin) {
        super(plugin, 3, 4);
    }

    @Override
    public ArrayList<ItemStack> getRequiredItemsForNextLevel() {
        ArrayList<ItemStack> requiredItems = new ArrayList<>();

        // generated by ChatGPT
        requiredItems.add(new ItemStack(Material.TUFF, 40 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.MANGROVE_LOG, 23 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.DRIPSTONE_BLOCK, 4 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.PUMPKIN, 64 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.COOKED_SALMON, 7 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.GOLD_INGOT, 19 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.WARPED_WART_BLOCK, 19 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.CHERRY_SAPLING, 37 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.FLINT, 34 * Main.properties.getNumberOfPlayers()));
        requiredItems.add(new ItemStack(Material.DEEPSLATE, 90 * Main.properties.getNumberOfPlayers()));

        return requiredItems;
    }

    @Override
    public void justUpgraded() {

    }

    @Override
    public int getRouletteGamePrice() {
        return 800;
    }

    @Override
    public LandlordEvent getEventToStartBeforeLevel() {
        return null;
    }

    @Override
    public Book getBook() {
        Book book = new Book("S3L4");
        book.addPage(LangDict.getString("levelBooks.season3.level4.page1"));
        book.addPage(LangDict.getString("levelBooks.endSignature"));
        return book;
    }
}
