name: Landlord
version: 2.0
author: Johan Svartdal
main: com.johansvartdal.landlord.Main
description: Landlord plugin.

commands:
  buychunk:
    description: Buy a chunk
  day:
    description: turns off rain and turns night into day!
  bal:
    description: Get Balance of player
    usage: /bal
  claimbonus:
    description: Claim your daily reward
  landlord:
    description: Start the game
    usage: /landlord <start>
  trade:
    description: Teleports to the trading area
    usage: /trade
  home:
    description: Teleports you home
    usage: /home
  donate:
    description: Donates the current item in hand to the Landlord
    usage: /donate
  upgrade:
    description: Progress to the next level
    usage: /upgrade [ info | accept ]
