name: Landlord
version: 2.0
author: Johan Svartdal
main: com.johansvartdal.landlord.Main
description: Landlord plugin.
api-version: 1.19

commands:
  buychunk:
    description: Buy a chunk
    usage: /buychunk [ now | info ]
  day:
    description: turns off rain and turns night into day!
  bal:
    description: Get Balance of player
    usage: /bal
  claimbonus:
    description: Claim your daily reward
  landlord:
    description: Start the game
    usage: /landlord [ start ]
  trade:
    description: Teleports to the trading area
    usage: /trade
  settrade:
    description: Defines a new trade location
    usage: /settrade
  home:
    description: Teleports you home
    usage: /home
  sethome:
    description: Defines a new home
    usage: /sethome
  donate:
    description: Donates the current item in hand to the Landlord
    usage: /donate
  upgrade:
    description: Progress to the next level
    usage: /upgrade [ info | accept ]
  sell:
    description: Sells the item in your hand
    usage: /sell [ all | info ]
  stocks:
    description: Buy or sell stocks
    usage: /stocks [ buy | sell | info ]
  joinroulette:
    description: Joins the roulette
    usage: /joinroulette
  capture:
    description: Capture an animal close to you
    usage: /capture
  wilderness:
    description: Teleport to wilderness
    usage: /wilderness
  visit:
    description: Visit another player
    usage: /visit [ accept | reject | [username] ]
  sendhome:
    description: Send a player home from your chunk
    usage: /sendhome [username]
  adm:
    description: Admin commands
    usage: /adm
  treasury:
    description: Commands regarding treasury
    usage: /treasury
  changelang:
    description: Change the language of Landlord
    usage: /changelang [ language_code ]
  fly:
    description: Enables you to fly
    usage: /fly [ now | end | info ]
  rent:
    description: Allows you to rent something
    usage: /rent [ name ]
